<<<<<<< HEAD
import os
from pathlib import Path

from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-your-secret-key-here-change-in-production'
=======
"""
Django settings for simplechatbot project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)r-c%5%5oie=ez17a72*c9fr(qg&&ui30t7h=s!b&9fvttvce^'
>>>>>>> d10c5186e931ca71dcb6a7f891bfc6f6fa302c54

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

<<<<<<< HEAD
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Or your SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'pavithrachandrasekar9360@gmail.com'  # Your email
EMAIL_HOST_PASSWORD = 'lcve skiw muvj atms'  # Gmail app password
DEFAULT_FROM_EMAIL = 'pavithrachandrasekar9360@gmail.com'
NOTIFICATION_EMAIL = 'pavithrachandrasekar9360@gmail.com'  # Where notifications go




# Application definition
=======
ALLOWED_HOSTS = []


# Application definition

>>>>>>> d10c5186e931ca71dcb6a7f891bfc6f6fa302c54
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
    'botapp'  
=======
    'bot'
>>>>>>> d10c5186e931ca71dcb6a7f891bfc6f6fa302c54
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
<<<<<<< HEAD
    'django.contrib.sessions.middleware.SessionMiddleware',  # Must have this
=======
    'django.contrib.sessions.middleware.SessionMiddleware',
>>>>>>> d10c5186e931ca71dcb6a7f891bfc6f6fa302c54
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'simplechatbot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
<<<<<<< HEAD
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
=======
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
>>>>>>> d10c5186e931ca71dcb6a7f891bfc6f6fa302c54
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
<<<<<<< HEAD
            'debug': True,  # Keep this for development
=======
>>>>>>> d10c5186e931ca71dcb6a7f891bfc6f6fa302c54
        },
    },
]

<<<<<<< HEAD


WSGI_APPLICATION = 'simplechatbot.wsgi.application'

# Database
=======
WSGI_APPLICATION = 'simplechatbot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

>>>>>>> d10c5186e931ca71dcb6a7f891bfc6f6fa302c54
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

<<<<<<< HEAD
# Password validation
=======

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

>>>>>>> d10c5186e931ca71dcb6a7f891bfc6f6fa302c54
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

<<<<<<< HEAD
# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Project-level static files
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files (for file uploads if needed)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEBUG = True
TEMPLATES[0]['OPTIONS']['debug'] = True
=======

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
>>>>>>> d10c5186e931ca71dcb6a7f891bfc6f6fa302c54
